import { DealStage, TaskStatus, Priority } from "@prisma/client";

export const dummyContacts = [
  {
    firstName: "Alice",
    lastName: "Johnson",
    email: "alice.johnson@example.com",
    phone: "123-456-7890",
    company: "Alpha Corp",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    firstName: "Bob",
    lastName: "Smith",
    email: "bob.smith@example.com",
    phone: "987-654-3210",
    company: "Beta Ltd",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    firstName: "Charlie",
    lastName: "Williams",
    email: "charlie.williams@example.com",
    phone: "111-222-3333",
    company: "Gamma LLC",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    firstName: "Diana",
    lastName: "Brown",
    email: "diana.brown@example.com",
    phone: "444-555-6666",
    company: "Delta Inc",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    firstName: "Edward",
    lastName: "Green",
    email: "edward.green@example.com",
    phone: "333-444-5555",
    company: "Emerald Solutions",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    firstName: "Fiona",
    lastName: "White",
    email: "fiona.white@example.com",
    phone: "222-333-4444",
    company: "Frost Tech",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    firstName: "George",
    lastName: "King",
    email: "george.king@example.com",
    phone: "777-888-9999",
    company: "Galaxy Systems",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    firstName: "Hannah",
    lastName: "Scott",
    email: "hannah.scott@example.com",
    phone: "888-999-0000",
    company: "Horizon Ventures",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    firstName: "Ian",
    lastName: "Clark",
    email: "ian.clark@example.com",
    phone: "111-333-5555",
    company: "Infinity Corp",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    firstName: "Jane",
    lastName: "Lopez",
    email: "jane.lopez@example.com",
    phone: "222-444-6666",
    company: "Jupiter Systems",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    firstName: "Kevin",
    lastName: "Turner",
    email: "kevin.turner@example.com",
    phone: "333-555-7777",
    company: "Keystone Ltd",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    firstName: "Laura",
    lastName: "Hill",
    email: "laura.hill@example.com",
    phone: "444-666-8888",
    company: "Legacy Group",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    firstName: "Mike",
    lastName: "Adams",
    email: "mike.adams@example.com",
    phone: "555-777-9999",
    company: "Matrix Solutions",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    firstName: "Nina",
    lastName: "Baker",
    email: "nina.baker@example.com",
    phone: "666-888-0000",
    company: "Nova Tech",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
];

export const dummyLeads = [
  {
    name: "Olivia Parker",
    company: "Omega Systems",
    email: "olivia.parker@example.com",
    phone: "101-202-3030",
    source: "Website",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    name: "Patrick Murphy",
    company: "Phoenix Ltd",
    email: "patrick.murphy@example.com",
    phone: "404-505-6060",
    source: "Event",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    name: "Quinn Mitchell",
    company: "Quantum Corp",
    email: "quinn.mitchell@example.com",
    phone: "707-808-9090",
    source: "Referral",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    name: "Rachel Reed",
    company: "Rocket Enterprises",
    email: "rachel.reed@example.com",
    phone: "123-123-1234",
    source: "Website",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    name: "Sam Carter",
    company: "Solaris Tech",
    email: "sam.carter@example.com",
    phone: "456-456-4567",
    source: "Cold Call",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    name: "Tina Brooks",
    company: "Titan Ventures",
    email: "tina.brooks@example.com",
    phone: "789-789-7890",
    source: "Email Campaign",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    name: "Umar Patel",
    company: "Umbrella Solutions",
    email: "umar.patel@example.com",
    phone: "654-321-9876",
    source: "Social Media",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    name: "Vera Cruz",
    company: "Velocity Corp",
    email: "vera.cruz@example.com",
    phone: "888-222-4444",
    source: "Referral",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    name: "William Ross",
    company: "Wave Systems",
    email: "william.ross@example.com",
    phone: "999-333-5555",
    source: "Conference",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    name: "Xavier Gomez",
    company: "Xplore Technologies",
    email: "xavier.gomez@example.com",
    phone: "111-444-7777",
    source: "Event",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    name: "Yasmine Flores",
    company: "Yellowstone Inc",
    email: "yasmine.flores@example.com",
    phone: "333-666-9999",
    source: "Website",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    name: "Zack Harper",
    company: "Zenith Ltd",
    email: "zack.harper@example.com",
    phone: "555-888-1111",
    source: "Referral",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    name: "Abby Lane",
    company: "Atlas Corp",
    email: "abby.lane@example.com",
    phone: "666-999-2222",
    source: "Webinar",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
  {
    name: "Brian Knight",
    company: "Blaze Systems",
    email: "brian.knight@example.com",
    phone: "777-000-3333",
    source: "Cold Call",
    userId: "cma1fsqvm0008txgkou7wj0ia",
  },
];

export const dummyDeals = dummyContacts.map((contact, index) => ({
  title: `Deal with ${contact.company}`,
  value: 5000 + index * 1000,
  customer: contact.company,
  stage: Object.values(DealStage)[index % Object.values(DealStage).length],
  expectedClose: new Date(
    new Date().setDate(new Date().getDate() + 15 + index),
  ),
  userId: "cma1fsqvm0008txgkou7wj0ia",
}));

export const dummyTasks = dummyContacts.map((contact, index) => ({
  subject: `Follow up with ${contact.firstName}`,
  dueDate: new Date(new Date().setDate(new Date().getDate() + 5 + index)),
  status: Object.values(TaskStatus)[index % Object.values(TaskStatus).length],
  priority: Object.values(Priority)[index % Object.values(Priority).length],
  description: `Discussion regarding ${contact.company}`,
  userId: "cma1fsqvm0008txgkou7wj0ia",
}));
